default:
    image: node:12.18.0 

stages:
    - build
    - deploy
    - set_version

workflow:
    rules: 
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_TITLE !~ /Increase version to.*/
          when: always

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "pipeline@collabos"
    - git config --global user.name "Pipeline"

build app:
    stage: build
    image: node_for_app
    script:
        - echo "Build app..."
        - git clone -b frontend --single-branch  zeevaa@zeevaa.git.backlog.com:/NEW_CP2021/NEW_CP2021.git
        - cd NEW_CP2021/04_Programs/frontend
        - npm config set registry http://registry.npmjs.org/
        - npm  cache clear --force
        - npm install
        - npm run build:winonlinux
        - zip -r "softphone_$(node -pe "require('./package.json')['version']").zip" dist
        - cp *.zip /app
        - echo "Output file is located at /home/tma/app/softphone_$(node -pe "require('./package.json')['version']").zip"

