default:
    image: node:12.18.0 

stages:
    - build
    - deploy
    - set_version

workflow:
    rules: 
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_TITLE !~ /Increase version to.*/
          when: always

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "pipeline@collabos"
    - git config --global user.name "Pipeline"

build web:
    stage: build
    script:
        - echo "Build web..."
        - git clone -b frontend --single-branch  zeevaa@zeevaa.git.backlog.com:/NEW_CP2021/NEW_CP2021.git
        - cd NEW_CP2021/04_Programs/frontend
        - npm version patch -m "Increase version to %s"
        - git push
        - npm install --unsafe-perm
        - npm run build
    artifacts:
        expire_in: 1 hr
        paths:
            - NEW_CP2021/04_Programs/frontend/build/


deploy web:
    stage: deploy
    script:
        - echo "Deploy web..."
        - echo "$SSH_PRIVATE_KEY_EC2" >> key.pem
        - chmod 700 key.pem
        - ssh -i key.pem ubuntu@3.114.97.64 rm -rf build/*
        - scp -r -i key.pem NEW_CP2021/04_Programs/frontend/build/* ubuntu@3.114.97.64:~/build
    dependencies:
        - build web

