default:
    image: node:12.18.0 

variables:
  BUILD_APP: $BUILD_APP

stages:
    - build
    - deploy
    - set_version

workflow:
    rules: 
        - if: '$CI_PIPELINE_SOURCE == "push"'
          when: never
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_TITLE !~ /Increase version to.*/
          when: always

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "pipeline@collabos"
    - git config --global user.name "Pipeline"
    - echo "$BUILD_APP"

build web:
    stage: build
    script:
        - echo "Build web..."
        - git clone -b "$CI_COMMIT_BRANCH" --single-branch  git@gitlab.tma.com.vn:vthienvu/collabos.git
        - cd collabos
        - npm install
        - npm run build
    artifacts:
        expire_in: 1 hr
        paths:
            - collabos/build/


deploy web:
    stage: deploy
    script:
        - echo "Deploy web..."
        - echo "$SSH_PRIVATE_KEY_EC2" >> key.pem
        - chmod 700 key.pem
        - rm -rf build/*
        - scp -r -i key.pem collabos/build/* ubuntu@3.114.97.64:~/build
    dependencies:
        - build web

build app:
    stage: build
    image: node_for_app
    rules:
        - if: '"$BUILD_APP" == "true"'
          when: always
    script:
        - echo "Build app..."
        - git clone -b "$CI_COMMIT_BRANCH" --single-branch  git@gitlab.tma.com.vn:vthienvu/collabos.git
        - cd collabos
        - npm  cache clear --force
        - npm install
        - npm run build:winonlinux
        - zip -r "softphone_$(node -pe "require('./package.json')['version']").zip" dist
        - cp *.zip /app
        - echo "Output file is located at /home/tma/app/softphone_$(node -pe "require('./package.json')['version']").zip"

set version:
    stage: set_version
    script:
        - echo "Increase package.json version..."
        - git clone -b "$CI_COMMIT_BRANCH" --single-branch  git@gitlab.tma.com.vn:vthienvu/collabos.git
        - cd collabos
        - npm version patch -m "Increase version to %s"
        - git push
    dependencies: []
