image: node:12.18.0 

stages:
    - deploy

workflow:
    rules: 
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: never
        - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "backend_master"
          when: always

before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "pipeline@collabos"
    - git config --global user.name "Pipeline"

build backend:
    stage: deploy
    script:
        - echo "Build backend..."
        - echo "$SSH_PRIVATE_KEY_BACKEND_EC2" >> key.pem
        - chmod 700 key.pem
        - git clone -b "$CI_COMMIT_BRANCH" --single-branch  git@gitlab.tma.com.vn:vthienvu/collabos.git
        - chmod +x collabos/runscript.sh
        - ssh -i key.pem ubuntu@18.180.191.58 rm -rf collabos/*
        - scp -r -i key.pem collabos/* ubuntu@18.180.191.58:collabos
        - ssh -i key.pem ubuntu@18.180.191.58 "./collabos/runscript.sh"
