"""change type token table

Revision ID: 01c6ae644d8e
Revises: 807caab6d11d
Create Date: 2022-03-19 22:02:46.364165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c6ae644d8e'
down_revision = '807caab6d11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
