"""change type token table

Revision ID: 0b9816ef1b1d
Revises: 01c6ae644d8e
Create Date: 2022-03-19 22:03:20.632586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9816ef1b1d'
down_revision = '01c6ae644d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
