"""first commit

Revision ID: 19dd53c64463
Revises: 0d1a828e24bb
Create Date: 2022-03-21 10:39:12.886884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dd53c64463'
down_revision = '0d1a828e24bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
