"""change type token table

Revision ID: 2122926d2a4c
Revises: 0b9816ef1b1d
Create Date: 2022-03-19 22:13:55.822488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2122926d2a4c'
down_revision = '0b9816ef1b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
