"""first commit

Revision ID: 3fd74249bcd7
Revises: e4b292a0851a
Create Date: 2022-03-21 16:00:38.861954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd74249bcd7'
down_revision = 'e4b292a0851a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
