"""commit

Revision ID: 4887f44bd2b5
Revises: 
Create Date: 2022-03-24 14:59:34.503115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4887f44bd2b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('tenant_id', sa.String(length=256), nullable=False, comment='tenant_id : id of tenant'),
    sa.Column('tenant_name', sa.String(length=256), nullable=True, comment=' tenant_name : name of tenant'),
    sa.Column('domain', sa.String(length=45), nullable=True, comment='domain : domain of tenant,'),
    sa.Column('prefix', mysql.INTEGER(display_width=11), nullable=True, comment='prefix : prefix of tenant, ex a number as 01, 02 '),
    sa.Column('identifier', sa.String(length=256), nullable=True, comment='identifier : identifier of tenant, ex ABC-01a'),
    sa.Column('channel_cnt', mysql.INTEGER(display_width=11), nullable=True, comment='channel_cnt : number of maximum channel of tenant'),
    sa.Column('use_speech_to_text', mysql.TINYINT(display_width=4), nullable=True, comment='use_speech_to_text : 0 is off, 1 is on speech_to_text'),
    sa.Column('st_engine', mysql.INTEGER(display_width=11), nullable=True, comment='st_engine : Choose between Ami voice or Google speak to text'),
    sa.Column('insert_date', sa.DateTime(), nullable=True, comment='insert_date : registration date'),
    sa.Column('update_date', sa.DateTime(), nullable=True, comment='update_date : Last time tenant is changed'),
    sa.PrimaryKeyConstraint('tenant_id'),
    comment='Tenant : All information about tenant'
    )
    op.create_table('authority',
    sa.Column('auth_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=True, comment='Tenant ID'),
    sa.Column('auth_name', sa.String(length=256), nullable=False),
    sa.Column('use_monitor', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('use_address', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_address', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_address', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_address', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_address', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_responding', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_responding', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_responding', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_responding', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_responding', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_message', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_message', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_message', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_message', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_message', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_dashboard', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_dashboard', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_dashboard', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_report', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_report', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_report', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_report', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_report', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_user', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_user', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_user', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_user', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_user', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_group', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_group', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_group', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_group', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_group', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_auth', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_auth', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_auth', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_auth', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('use_flow', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_flow', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_flow', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('use_seat', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_seat', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_seat', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_seat', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_chat', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('scope_chat', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('use_speech', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_speech', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_speech', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('use_trigger', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_trigger', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('del_trigger', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('use_config', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('edit_config', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('use_log', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('dl_log', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_index(op.f('ix_authority_tenant_id'), 'authority', ['tenant_id'], unique=False)
    op.create_table('settings',
    sa.Column('setting_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('speech_ext', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('recording_type', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('list_cnt_users', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_groups', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_auth', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_projects', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_skills', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_skillassign', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_flows', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_business_hours', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_announcements', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_talkscripts', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_triggers', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_address', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_speech', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_rreports', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_seatviews', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_hreports', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_dashboards', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_respondings', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_voicemails', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_sms', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('list_cnt_operation_logs', mysql.INTEGER(display_width=11), server_default=sa.text('10'), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('setting_id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='id'),
    sa.Column('tenant_id', sa.String(length=256), nullable=False, comment='Tenant Id'),
    sa.Column('user_id', mysql.VARCHAR(length=256), nullable=False, comment='User ID'),
    sa.Column('user_name', mysql.VARCHAR(length=256), nullable=True, comment='Username : Username is used to login collabos by user'),
    sa.Column('password', mysql.VARCHAR(length=1024), nullable=True, comment='Password'),
    sa.Column('mail', mysql.VARCHAR(length=256), nullable=True, comment='Email : Email address of user'),
    sa.Column('group_id', mysql.VARCHAR(length=256), nullable=True, comment='Group Id : Id of group which user is belong to'),
    sa.Column('device', mysql.INTEGER(display_width=11), nullable=True, comment='Device : Device that user is using'),
    sa.Column('autoin_time', mysql.INTEGER(display_width=11), nullable=True, comment='Auto In Time : Time that after ending call, user can receive new call'),
    sa.Column('auth_id', mysql.BIGINT(display_width=20), nullable=True, comment='Authority Id : privilege that user is permitted what features to use'),
    sa.Column('extension', sa.String(length=64), nullable=True, comment='Extension Number : Extension number is number that end-user can contact with user via it'),
    sa.Column('locked', mysql.TINYINT(display_width=1), nullable=True, comment='Lock State : 0 is not locked, 1 is locked'),
    sa.Column('locked_date', sa.DateTime(), nullable=True, comment='Locked date : Last date that state of user is locked'),
    sa.Column('login_ng_cnt', mysql.INTEGER(display_width=11), nullable=True, comment='Login fail consecutive : Number of time that user logged in collabos fail in row'),
    sa.Column('user_classifier', mysql.INTEGER(display_width=11), nullable=True, comment='User Classification : 0 is normal user, 1 is tenant user, 2 is collabos adminitrator'),
    sa.Column('insert_date', sa.DateTime(), nullable=True, comment='Insert Date : Time that user is created'),
    sa.Column('update_date', sa.DateTime(), nullable=True, comment='Update Date : Last time that user info is changed'),
    sa.Column('firstname', mysql.VARCHAR(length=1024), nullable=True, comment='First Name'),
    sa.Column('lastname', mysql.VARCHAR(length=1024), nullable=True, comment='Last Name'),
    sa.Column('middlename', mysql.VARCHAR(length=1024), nullable=True, comment='Middle Name'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id', 'tenant_id', 'user_id'),
    sa.UniqueConstraint('id'),
    comment='Users : User information'
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('group_id', sa.String(length=256), nullable=False),
    sa.Column('group_name', sa.String(length=256), nullable=True),
    sa.Column('auth_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('autoin_time', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['authority.auth_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'group_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('token',
    sa.Column('user_id', mysql.VARCHAR(length=256), nullable=False, comment='User Id'),
    sa.Column('token_id', mysql.VARCHAR(length=60), nullable=True, comment='Token Id : Each user has an unique token_id'),
    sa.Column('expired_date', mysql.BIGINT(display_width=20), nullable=True, comment='Expired Time : Expired time of token'),
    sa.Column('create_date', sa.DateTime(), nullable=True, comment='Create Date : Created Date of token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('token_id'),
    comment='Token : Manage token of each user for authentication'
    )
    op.create_index(op.f('ix_token_user_id'), 'token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_user_id'), table_name='token')
    op.drop_table('token')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_authority_tenant_id'), table_name='authority')
    op.drop_table('authority')
    op.drop_table('tenant')
    # ### end Alembic commands ###
