"""change type token table5

Revision ID: 48c5d280dba1
Revises: 8a3b83d3c10f
Create Date: 2022-03-19 23:58:50.953208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c5d280dba1'
down_revision = '8a3b83d3c10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
