"""your message

Revision ID: 4aebaaa61a24
Revises: 3d6e5074e00b
Create Date: 2022-03-16 11:32:52.864389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4aebaaa61a24'
down_revision = '3d6e5074e00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_files',
    sa.Column('sound_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('sound_name', sa.String(length=256), nullable=False),
    sa.Column('location_path', sa.Text(), nullable=True),
    sa.Column('sound_type', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.UniqueConstraint('sound_id')
    )
    op.create_table('sound_setting',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('outside_sound_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('outside_volume', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('extension_sound_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('extension_volume', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('hold_sound_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('hold_volume', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('sound_quality', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sound_setting')
    op.drop_table('sound_files')
    # ### end Alembic commands ###