"""change type token table

Revision ID: 5252e209958b
Revises: 2122926d2a4c
Create Date: 2022-03-19 22:14:35.780609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5252e209958b'
down_revision = '2122926d2a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
