"""change type token table6

Revision ID: 78a3dab00398
Revises: 48c5d280dba1
Create Date: 2022-03-20 00:01:57.730574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a3dab00398'
down_revision = '48c5d280dba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
