"""trying1

Revision ID: 807caab6d11d
Revises: 
Create Date: 2022-03-18 14:24:10.758175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '807caab6d11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('call_record_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('from_addr', sa.String(length=64), nullable=True),
    sa.Column('to_addr', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('skill_start_date', sa.DateTime(), nullable=True),
    sa.Column('answer_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('total_time', sa.Time(), nullable=True),
    sa.Column('talk_time', sa.Time(), nullable=True),
    sa.Column('result', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('call_id', sa.String(length=1024), nullable=True),
    sa.Column('unique_id', sa.String(length=1024), nullable=True),
    sa.Column('hold_time', sa.Time(), nullable=True),
    sa.Column('hold_cnt', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('proc_time', sa.Time(), nullable=True),
    sa.Column('wait_time', sa.Time(), nullable=True),
    sa.Column('ring_time', sa.Time(), nullable=True),
    sa.Column('skill_id', sa.String(length=256), nullable=True),
    sa.Column('transfer', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('transferred', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('passobj', mysql.LONGTEXT(), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('group_id', sa.String(length=256), nullable=True),
    sa.Column('direction', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('memo_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('memo_free', sa.String(length=512), nullable=True),
    sa.Column('acw_time', sa.Time(), nullable=True),
    sa.Column('project_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('sla_ans', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('call_record_id'),
    sa.UniqueConstraint('call_record_id')
    )
    op.create_table('tenant',
    sa.Column('tenant_id', sa.String(length=256), nullable=False, comment='tenant_id : id of tenant'),
    sa.Column('tenant_name', sa.String(length=256), nullable=True, comment=' tenant_name : name of tenant'),
    sa.Column('domain', sa.String(length=45), nullable=True, comment='domain : domain of tenant,'),
    sa.Column('prefix', mysql.INTEGER(display_width=11), nullable=True, comment='prefix : prefix of tenant, ex a number as 01, 02 '),
    sa.Column('identifier', sa.String(length=256), nullable=True, comment='identifier : identifier of tenant, ex ABC-01a'),
    sa.Column('channel_cnt', mysql.INTEGER(display_width=11), nullable=True, comment='channel_cnt : number of maximum channel of tenant'),
    sa.Column('use_speech_to_text', mysql.TINYINT(display_width=4), nullable=True, comment='use_speech_to_text : 0 is off, 1 is on speech_to_text'),
    sa.Column('st_engine', mysql.INTEGER(display_width=11), nullable=True, comment='st_engine : Choose between Ami voice or Google speak to text'),
    sa.Column('insert_date', sa.DateTime(), nullable=True, comment='insert_date : registration date'),
    sa.Column('update_date', sa.DateTime(), nullable=True, comment='update_date : Last time tenant is changed'),
    sa.PrimaryKeyConstraint('tenant_id'),
    comment='Tenant : All information about tenant'
    )
    op.create_table('user_records',
    sa.Column('user_record_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('acd_status', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('aux_detail', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('incoming_skill', sa.String(length=256), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_record_id'),
    sa.UniqueConstraint('user_record_id')
    )
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False, comment='id'),
    sa.Column('tenant_id', sa.String(length=256), nullable=False, comment='Tenant Id'),
    sa.Column('user_id', mysql.VARCHAR(length=256), nullable=False, comment='User ID'),
    sa.Column('user_name', mysql.VARCHAR(length=256), nullable=True, comment='Username : Username is used to login collabos by user'),
    sa.Column('password', mysql.VARCHAR(length=1024), nullable=True, comment='Password'),
    sa.Column('mail', mysql.VARCHAR(length=256), nullable=True, comment='Email : Email address of user'),
    sa.Column('group_id', mysql.VARCHAR(length=256), nullable=True, comment='Group Id : Id of group which user is belong to'),
    sa.Column('device', mysql.INTEGER(display_width=11), nullable=True, comment='Device : Device that user is using'),
    sa.Column('autoin_time', mysql.INTEGER(display_width=11), nullable=True, comment='Auto In Time : Time that after ending call, user can receive new call'),
    sa.Column('auth_id', mysql.BIGINT(display_width=20), nullable=True, comment='Authority Id : privilege that user is permitted what features to use'),
    sa.Column('extension', sa.String(length=64), nullable=True, comment='Extension Number : Extension number is number that end-user can contact with user via it'),
    sa.Column('locked', mysql.TINYINT(display_width=1), nullable=True, comment='Lock State : 0 is not locked, 1 is locked'),
    sa.Column('locked_date', sa.DateTime(), nullable=True, comment='Locked date : Last date that state of user is locked'),
    sa.Column('login_ng_cnt', mysql.INTEGER(display_width=11), nullable=True, comment='Login fail consecutive : Number of time that user logged in collabos fail in row'),
    sa.Column('user_classifier', mysql.INTEGER(display_width=11), nullable=True, comment='User Classification : 0 is normal user, 1 is tenant user, 2 is collabos adminitrator'),
    sa.Column('insert_date', sa.DateTime(), nullable=True, comment='Insert Date : Time that user is created'),
    sa.Column('update_date', sa.DateTime(), nullable=True, comment='Update Date : Last time that user info is changed'),
    sa.Column('firstname', mysql.VARCHAR(length=1024), nullable=True, comment='First Name'),
    sa.Column('lastname', mysql.VARCHAR(length=1024), nullable=True, comment='Last Name'),
    sa.Column('middlename', mysql.VARCHAR(length=1024), nullable=True, comment='Middle Name'),
    sa.Column('project_id', mysql.BIGINT(display_width=20), nullable=True, comment='Project Id : Project which user is belong'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('id', 'tenant_id', 'user_id'),
    sa.UniqueConstraint('id'),
    comment='Users : User information'
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('token',
    sa.Column('user_id', mysql.VARCHAR(length=256), nullable=False, comment='User Id'),
    sa.Column('token_id', mysql.VARCHAR(length=60), nullable=True, comment='Token Id : Each user has an unique token_id'),
    sa.Column('expired_date', mysql.INTEGER(display_width=11), nullable=True, comment='Expired Time : Expired time of token'),
    sa.Column('create_date', mysql.INTEGER(display_width=11), nullable=True, comment='Create Date : Created Date of token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('token_id'),
    comment='Token : Manage token of each user for authentication'
    )
    op.create_index(op.f('ix_token_user_id'), 'token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_user_id'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_records')
    op.drop_table('tenant')
    op.drop_table('call_records')
    # ### end Alembic commands ###
