"""change type token table4

Revision ID: 8a3b83d3c10f
Revises: 97ce5cfd7599
Create Date: 2022-03-19 22:20:33.929472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3b83d3c10f'
down_revision = '97ce5cfd7599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
