"""message

Revision ID: 937c659c8cb3
Revises: 94b709c365bb
Create Date: 2022-03-20 14:53:49.504202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '937c659c8cb3'
down_revision = '94b709c365bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_files',
    sa.Column('sound_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('sound_name', sa.String(length=256), nullable=False),
    sa.Column('location_path', sa.Text(), nullable=True),
    sa.Column('sound_type', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('insert_data', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_data', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('sound_id'),
    sa.UniqueConstraint('sound_id')
    )
    op.create_table('sound_setting',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('outside_sound_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('outside_volume', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('extension_sound_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('extension_volume', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('hold_sound_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('hold_volume', mysql.INTEGER(display_width=11), server_default=sa.text('1'), nullable=True),
    sa.Column('sound_quality', mysql.INTEGER(display_width=11), server_default=sa.text('0'), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correspondence_memo',
    sa.Column('correspondence_memo_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('correspondence_memo_tag', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('correspondence_memo_explaination', sa.String(length=45), nullable=True),
    sa.Column('last_change_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('correspondence_memo_id')
    )
    op.create_index(op.f('ix_correspondence_memo_tenant_id'), 'correspondence_memo', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correspondence_memo_tenant_id'), table_name='correspondence_memo')
    op.drop_table('correspondence_memo')
    op.drop_table('sound_setting')
    op.drop_table('sound_files')
    # ### end Alembic commands ###
