"""change type token table7

Revision ID: 94b709c365bb
Revises: 78a3dab00398
Create Date: 2022-03-20 00:04:02.258349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b709c365bb'
down_revision = '78a3dab00398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
