"""change type token table2

Revision ID: 97ce5cfd7599
Revises: 5252e209958b
Create Date: 2022-03-19 22:19:39.899984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ce5cfd7599'
down_revision = '5252e209958b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Token', 'expired_date',
                    existing_type=sa.INTEGER,
                    type_=sa.BIGINT)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logics', 'id',
                    existing_type=sa.BIGINT,
                    type_=sa.INTEGER)
    # ### end Alembic commands ###
