"""message

Revision ID: 9a15882c86b7
Revises: ac1e5904bc03
Create Date: 2022-03-22 21:31:45.965064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a15882c86b7'
down_revision = 'ac1e5904bc03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_records', sa.Column('sub_status', mysql.INTEGER(display_width=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_records', 'sub_status')
    # ### end Alembic commands ###
