"""hope1

Revision ID: a9071d7c582d
Revises: dd93b78e9cb4
Create Date: 2022-03-16 18:22:41.547832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9071d7c582d'
down_revision = 'dd93b78e9cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
