"""first commit

Revision ID: c196ca8a5185
Revises: 3fd74249bcd7
Create Date: 2022-03-21 16:09:45.258789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c196ca8a5185'
down_revision = '3fd74249bcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caller_id_users',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('caller_num_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('caller_ids',
    sa.Column('caller_num_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=256), nullable=False),
    sa.Column('project_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('caller_num', sa.String(length=64), nullable=True),
    sa.Column('caller_num_name', sa.String(length=256), nullable=True),
    sa.Column('prefix_num', sa.String(length=32), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('caller_num_id'),
    sa.UniqueConstraint('caller_num_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caller_ids')
    op.drop_table('caller_id_users')
    # ### end Alembic commands ###
