"""message1

Revision ID: dc97764ab03c
Revises: 955f0322ffe1
Create Date: 2022-03-20 22:51:38.988586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc97764ab03c'
down_revision = '955f0322ffe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responding_memo',
    sa.Column('memo_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tenant_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('memo_name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('update_date', sa.DateTime(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ),
    sa.PrimaryKeyConstraint('memo_id')
    )
    op.alter_column('users', 'sound_id',
               existing_type=mysql.INTEGER(),
               comment='Sound Id: ringtone which user have selected',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sound_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Sound Id: ringtone which user have selected',
               existing_nullable=True)
    op.drop_table('responding_memo')
    # ### end Alembic commands ###
