"""hope1

Revision ID: f0a7e38df36e
Revises: a9071d7c582d
Create Date: 2022-03-16 18:25:25.897753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a7e38df36e'
down_revision = 'a9071d7c582d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
